package org.voxrox.mailbackend.feature.mail.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Locale;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.voxrox.mailbackend.feature.account.entity.AccountEntity;
import org.voxrox.mailbackend.feature.mail.dto.AttachmentResponse;
import org.voxrox.mailbackend.feature.mail.dto.MailDetailResponse;
import org.voxrox.mailbackend.feature.mail.dto.MailSummaryResponse;
import org.voxrox.mailbackend.feature.mail.entity.AttachmentEntity;
import org.voxrox.mailbackend.feature.mail.entity.MessageEntity;

/**
 * Unit tests for {@link MessageMapper}.
 *
 * Pure unit-level logic with a real message bundle so the localized
 * placeholders are exercised end-to-end.
 */
@DisplayName("MessageMapper")
class MessageMapperTest {

    private static final LocalDateTime RECEIVED_AT = LocalDateTime.of(2025, 3, 10, 14, 30);

    private MessageMapper mapper;

    @BeforeEach
    void setUp() {
        ResourceBundleMessageSource messageSource = new ResourceBundleMessageSource();
        messageSource.setBasename("messages");
        messageSource.setDefaultEncoding("UTF-8");
        messageSource.setFallbackToSystemLocale(false);
        mapper = new MessageMapper(messageSource);
        LocaleContextHolder.setLocale(Locale.forLanguageTag("cs"));
    }

    @AfterEach
    void tearDown() {
        // Reset the thread-local locale so it does not leak into later tests
        // sharing the surefire fork.
        LocaleContextHolder.resetLocaleContext();
    }

    // --- Helper methods ---

    private AccountEntity createAccount() {
        var account = new AccountEntity();
        account.setId(1L);
        account.setAccountName("Test");
        account.setEmail("user@example.com");
        return account;
    }

    private MailDetailResponse createDto() {
        return new MailDetailResponse(null, // stableId - generated by the mapper
                42L, // uid
                "INBOX", // folderName — informational; toEntity takes the folder as a parameter
                "Test subject", "John Doe <john@example.com>", "recipient@example.com", "cc@example.com",
                "bcc@example.com", "<p>Message body</p>", RECEIVED_AT, true, // seen
                false, // flagged
                true, // answered
                "<msg-001@example.com>", "<reply-to@example.com>", "<ref1@example.com> <ref2@example.com>", false, // hasAttachments
                null, // attachments
                null, // contentError
                null); // threadId — assigned by ThreadingService, not by the fetch layer
    }

    private MailDetailResponse createDtoWithAttachments() {
        var attachments = List.of(new AttachmentResponse("1.1", "document.pdf", "application/pdf", 1024),
                new AttachmentResponse("1.2", "image.png", "image/png", 2048));

        return new MailDetailResponse(null, 42L, "INBOX", "Message with attachment", "sender@example.com",
                "recipient@example.com", null, null, null, RECEIVED_AT, false, true, false, "<msg-002@example.com>",
                null, null, true, attachments, null, null);
    }

    private MessageEntity createEntity() {
        var entity = new MessageEntity();
        entity.setId(100L);
        entity.setStableId("abc123def456");
        entity.setAccount(createAccount());
        entity.setFolderName("INBOX");
        entity.setUid(42L);
        entity.setUidValidity(12345L);
        entity.setSubject("Test subject");
        entity.setSender("John Doe <john@example.com>");
        entity.setRecipientsTo("recipient@example.com");
        entity.setRecipientsCc("cc@example.com");
        entity.setRecipientsBcc("bcc@example.com");
        entity.setContent("<p>Stored body</p>");
        entity.setReceivedAt(RECEIVED_AT);
        entity.setSeen(true);
        entity.setFlagged(false);
        entity.setAnswered(true);
        entity.setMessageId("<msg-001@example.com>");
        entity.setInReplyTo("<reply-to@example.com>");
        entity.setReferences("<ref1@example.com> <ref2@example.com>");
        entity.setHasAttachments(false);
        return entity;
    }

    private MessageEntity createEntityWithAttachments() {
        var entity = createEntity();
        entity.setHasAttachments(true);

        var att1 = new AttachmentEntity();
        att1.setPartPath("1.1");
        att1.setFileName("document.pdf");
        att1.setContentType("application/pdf");
        att1.setSize(1024);
        entity.addAttachment(att1);

        var att2 = new AttachmentEntity();
        att2.setPartPath("1.2");
        att2.setFileName("image.png");
        att2.setContentType("image/png");
        att2.setSize(2048);
        entity.addAttachment(att2);

        return entity;
    }

    @Nested
    @DisplayName("toEntity")
    class ToEntity {

        @Test
        @DisplayName("maps every field from the DTO onto the entity")
        void mapsAllFields() {
            // Arrange
            var dto = createDto();
            var account = createAccount();

            // Act
            MessageEntity result = mapper.toEntity(dto, account, "INBOX", 12345L);

            // Assert - metadata
            assertThat(result.getAccount()).isSameAs(account);
            assertThat(result.getFolderName()).isEqualTo("INBOX");
            assertThat(result.getUid()).isEqualTo(42L);
            assertThat(result.getUidValidity()).isEqualTo(12345L);

            // Assert - body
            assertThat(result.getSubject()).isEqualTo("Test subject");
            assertThat(result.getSender()).isEqualTo("John Doe <john@example.com>");
            assertThat(result.getRecipientsTo()).isEqualTo("recipient@example.com");
            assertThat(result.getRecipientsCc()).isEqualTo("cc@example.com");
            assertThat(result.getRecipientsBcc()).isEqualTo("bcc@example.com");
            assertThat(result.getContent()).isEqualTo("<p>Message body</p>");

            // Assert - flags and timestamp
            assertThat(result.getReceivedAt()).isEqualTo(RECEIVED_AT);
            assertThat(result.isSeen()).isTrue();
            assertThat(result.isFlagged()).isFalse();
            assertThat(result.isAnswered()).isTrue();

            // Assert - threading
            assertThat(result.getMessageId()).isEqualTo("<msg-001@example.com>");
            assertThat(result.getInReplyTo()).isEqualTo("<reply-to@example.com>");
            assertThat(result.getReferences()).isEqualTo("<ref1@example.com> <ref2@example.com>");

            // Assert - attachments
            assertThat(result.isHasAttachments()).isFalse();
            assertThat(result.getAttachments()).isEmpty();
        }

        @Test
        @DisplayName("generates a deterministic 32-char hex stableId from message identity")
        void generatesDeterministicStableId() {
            // Same inputs → same id, so a folder re-download (new random UUID before)
            // keeps the client's reference valid instead of 404-ing as a "ghost".
            MessageEntity first = mapper.toEntity(createDto(), createAccount(), "INBOX", 1L);
            MessageEntity second = mapper.toEntity(createDto(), createAccount(), "INBOX", 1L);

            assertThat(first.getStableId()).isNotNull().isNotBlank().hasSize(32).matches("[0-9a-f]{32}");
            assertThat(second.getStableId()).isEqualTo(first.getStableId());

            // Same message under a different folder (e.g. a Gmail label) → distinct id.
            MessageEntity otherFolder = mapper.toEntity(createDto(), createAccount(), "[Gmail]/All Mail", 1L);
            assertThat(otherFolder.getStableId()).isNotEqualTo(first.getStableId());
        }

        @Test
        @DisplayName("does not blow up when the DTO carries null attachments")
        void withNullAttachments_doesNotCrash() {
            // Arrange - dto with attachments == null
            var dto = createDto();
            assertThat(dto.attachments()).isNull(); // sanity check on the fixture

            // Act - must not throw
            MessageEntity result = mapper.toEntity(dto, createAccount(), "INBOX", 1L);

            // Assert
            assertThat(result.getAttachments()).isEmpty();
        }

        @Test
        @DisplayName("with attachments in the DTO, maps them onto the entity correctly")
        void withAttachments_mapsThemCorrectly() {
            // Arrange
            var dto = createDtoWithAttachments();

            // Act
            MessageEntity result = mapper.toEntity(dto, createAccount(), "INBOX", 1L);

            // Assert
            assertThat(result.isHasAttachments()).isTrue();
            assertThat(result.getAttachments()).hasSize(2);

            // First attachment
            var att1 = result.getAttachments().get(0);
            assertThat(att1.getPartPath()).isEqualTo("1.1");
            assertThat(att1.getFileName()).isEqualTo("document.pdf");
            assertThat(att1.getContentType()).isEqualTo("application/pdf");
            assertThat(att1.getSize()).isEqualTo(1024);
            assertThat(att1.getMessage()).isSameAs(result); // bidirectional link

            // Second attachment
            var att2 = result.getAttachments().get(1);
            assertThat(att2.getPartPath()).isEqualTo("1.2");
            assertThat(att2.getFileName()).isEqualTo("image.png");
        }
    }

    @Nested
    @DisplayName("toDto")
    class ToDto {

        @Test
        @DisplayName("maps the entity onto MailDetailResponse with the right content")
        void mapsEntityToDto() {
            // Arrange
            var entity = createEntity();
            String content = "<p>Fresh content from IMAP</p>";

            // Act
            MailDetailResponse result = mapper.toDto(entity, content);

            // Assert
            assertThat(result.stableId()).isEqualTo("abc123def456");
            assertThat(result.uid()).isEqualTo(42L);
            assertThat(result.subject()).isEqualTo("Test subject");
            assertThat(result.sender()).isEqualTo("John Doe <john@example.com>");
            assertThat(result.recipientsTo()).isEqualTo("recipient@example.com");
            assertThat(result.recipientsCc()).isEqualTo("cc@example.com");
            assertThat(result.recipientsBcc()).isEqualTo("bcc@example.com");
            assertThat(result.body()).isEqualTo(content);
            assertThat(result.receivedAt()).isEqualTo(RECEIVED_AT);
            assertThat(result.seen()).isTrue();
            assertThat(result.flagged()).isFalse();
            assertThat(result.answered()).isTrue();
            assertThat(result.messageId()).isEqualTo("<msg-001@example.com>");
            assertThat(result.inReplyTo()).isEqualTo("<reply-to@example.com>");
            assertThat(result.references()).isEqualTo("<ref1@example.com> <ref2@example.com>");
            assertThat(result.hasAttachments()).isFalse();
            assertThat(result.attachments()).isEmpty();
            assertThat(result.contentError()).isNull();
        }

        @Test
        @DisplayName("with contentError - populates the error message")
        void withContentError_populatesIt() {
            // Arrange
            var entity = createEntity();
            String cachedContent = "<p>Cached older version</p>";
            String error = "IMAP fetch failed: connection timeout";

            // Act
            MailDetailResponse result = mapper.toDto(entity, cachedContent, error);

            // Assert
            assertThat(result.body()).isEqualTo(cachedContent);
            assertThat(result.contentError()).isEqualTo("IMAP fetch failed: connection timeout");
        }

        @Test
        @DisplayName("missing subject/sender are localized only on output")
        void missingSubjectAndSenderAreLocalizedOnOutput() {
            var entity = createEntity();
            entity.setSubject(null);
            entity.setSender(null);
            LocaleContextHolder.setLocale(Locale.ENGLISH);

            MailDetailResponse result = mapper.toDto(entity, "<p>Body</p>");

            assertThat(result.subject()).isEqualTo("(No subject)");
            assertThat(result.sender()).isEqualTo("[Unknown sender]");
        }

        @Test
        @DisplayName("with attachments - maps them via AttachmentResponse.fromEntity")
        void withAttachments_mapsThemCorrectly() {
            // Arrange
            var entity = createEntityWithAttachments();

            // Act
            MailDetailResponse result = mapper.toDto(entity, null);

            // Assert
            assertThat(result.hasAttachments()).isTrue();
            assertThat(result.attachments()).hasSize(2);
            assertThat(result.attachments().get(0).fileName()).isEqualTo("document.pdf");
            assertThat(result.attachments().get(1).fileName()).isEqualTo("image.png");
        }
    }

    @Nested
    @DisplayName("withDisplayFallbacks")
    class WithDisplayFallbacks {

        private MailSummaryResponse rawSummary(String subject, String sender) {
            return new MailSummaryResponse(100L, "abc123def456", "INBOX", subject, sender, "recipient@example.com",
                    RECEIVED_AT, true, false, true, false, "thread-1", 42L);
        }

        @Test
        @DisplayName("returns the same instance when subject and sender are present")
        void passesThroughWhenComplete() {
            MailSummaryResponse raw = rawSummary("Test subject", "John Doe <john@example.com>");

            MailSummaryResponse result = mapper.withDisplayFallbacks(raw);

            assertThat(result).isSameAs(raw);
        }

        @Test
        @DisplayName("fills localized fallbacks for null subject and sender, keeping all other fields")
        void fillsFallbacksForNullFields() {
            MailSummaryResponse raw = rawSummary(null, null);

            MailSummaryResponse result = mapper.withDisplayFallbacks(raw);

            // The fallback strings come from MessageSource — assert they are
            // non-blank and different from the raw nulls, not their exact wording.
            assertThat(result.subject()).isNotBlank();
            assertThat(result.sender()).isNotBlank();
            assertThat(result.id()).isEqualTo(100L);
            assertThat(result.stableId()).isEqualTo("abc123def456");
            assertThat(result.folderName()).isEqualTo("INBOX");
            assertThat(result.recipientsTo()).isEqualTo("recipient@example.com");
            assertThat(result.receivedAt()).isEqualTo(RECEIVED_AT);
            assertThat(result.seen()).isTrue();
            assertThat(result.flagged()).isFalse();
            assertThat(result.answered()).isTrue();
            assertThat(result.hasAttachments()).isFalse();
            assertThat(result.threadId()).isEqualTo("thread-1");
            assertThat(result.uid()).isEqualTo(42L);
        }
    }
}
