<script lang="ts">
	import { isTauri } from '@tauri-apps/api/core';
	import { resolveResource } from '@tauri-apps/api/path';
	import { readTextFile } from '@tauri-apps/plugin-fs';
	import { _ } from '$lib/i18n/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Surface } from '$lib/components/ui/surface/index.js';

	/*
	 * The aggregated third-party NOTICE.txt (~100 KB, all npm/Maven/Cargo
	 * components) is bundled into the Tauri app resources — see
	 * `bundle.resources` in src-tauri/tauri.conf.json — and regenerated by
	 * `npm run regen:notice`. It is read on demand: most About visits never open
	 * it, so we avoid pulling 100 KB into the page on every render. Reveal uses a
	 * standard disclosure (aria-expanded button → region labelled by the heading)
	 * so the screen reader announces expand/collapse without adding a redundant
	 * region landmark. Outside the desktop app (browser / E2E mock) the bundled
	 * resource does not exist, so we show a short explanation instead of failing.
	 */
	let open = $state(false);
	let content = $state<string | null>(null);
	let loading = $state(false);
	let infoMessage = $state<string | null>(null);
	let errorMessage = $state<string | null>(null);

	async function toggleNotices() {
		if (open) {
			open = false;
			return;
		}
		infoMessage = null;
		errorMessage = null;
		if (content !== null) {
			open = true;
			return;
		}
		if (!isTauri()) {
			infoMessage = $_('settings.about.licenses.unsupported');
			return;
		}
		if (loading) return;
		loading = true;
		try {
			const path = await resolveResource('NOTICE.txt');
			content = await readTextFile(path);
			open = true;
		} catch {
			errorMessage = $_('settings.about.licenses.loadFailed');
		} finally {
			loading = false;
		}
	}
</script>

<Surface as="section" class="space-y-3">
	<h2 id="about-licenses-heading" class="text-sm font-semibold">
		{$_('settings.about.licenses.heading')}
	</h2>
	<p class="text-sm text-muted-foreground">{$_('settings.about.licenses.intro')}</p>

	<Button
		type="button"
		variant="outline"
		size="xs"
		onclick={toggleNotices}
		disabled={loading}
		aria-expanded={open}
		aria-controls="about-licenses-content"
	>
		{#if loading}
			{$_('settings.about.licenses.loading')}
		{:else if open}
			{$_('settings.about.licenses.hide')}
		{:else}
			{$_('settings.about.licenses.show')}
		{/if}
	</Button>

	{#if infoMessage}
		<p class="text-xs text-muted-foreground">{infoMessage}</p>
	{/if}
	{#if errorMessage}
		<Surface variant="danger" padding="sm">
			<p class="text-sm" role="alert">{errorMessage}</p>
		</Surface>
	{/if}

	{#if open && content}
		<textarea
			id="about-licenses-content"
			readonly
			aria-labelledby="about-licenses-heading"
			class="h-80 w-full resize-y rounded-md border border-border bg-muted/30 p-3 font-mono text-xs leading-relaxed"
			value={content}
		></textarea>
	{/if}
</Surface>
